import type { ChartType } from '../core';

/**
 * Which Customize controls apply to each chart type, measured by rendering every example with each
 * option set and checking whether the pixels changed (palette, scale, diverging, updown), plus
 * whether it has axes (cartesian: the grid toggle) and a legend.
 */
export const CUSTOM_FLAGS: Record<ChartType, string> = {
  line: 'palette legend cartesian',
  area: 'palette legend cartesian',
  bar: 'palette legend cartesian',
  histogram: 'palette cartesian',
  scatter: 'palette legend cartesian',
  bubble: 'palette legend cartesian',
  heatmap: 'scale legend diverging cartesian',
  candlestick: 'updown cartesian',
  pie: 'palette legend',
  donut: 'palette legend',
  radar: 'palette legend',
  gauge: '',
  bar3d: 'palette legend',
  scatter3d: 'palette legend',
  line3d: 'palette legend',
  surface3d: 'scale legend',
  lollipop: 'palette cartesian',
  dotplot: 'palette legend cartesian',
  dumbbell: 'palette legend cartesian',
  rangeBar: 'palette cartesian',
  bullet: 'palette',
  waterfall: 'palette updown legend cartesian',
  marimekko: 'palette legend cartesian',
  pictograph: 'palette',
  radialBar: 'palette legend',
  rangeArea: 'palette legend cartesian',
  slope: 'palette legend cartesian',
  bump: 'palette legend cartesian',
  horizon: 'diverging legend',
  sparkline: 'palette',
  radialLine: 'palette legend',
  box: 'palette cartesian',
  violin: 'palette cartesian',
  density: 'palette legend cartesian',
  ridgeline: 'palette cartesian',
  beeswarm: 'palette cartesian',
  strip: 'palette cartesian',
  ecdf: 'palette legend cartesian',
  qq: 'palette cartesian',
  semiDonut: 'palette legend',
  waffle: 'palette legend',
  funnel: 'palette',
  pyramid: 'palette legend',
  venn: 'palette legend',
  polarArea: 'palette',
  windRose: 'scale legend',
  treemap: 'palette legend',
  sunburst: 'palette legend',
  icicle: 'palette legend',
  pack: 'palette legend',
  dendrogram: 'palette legend',
  orgChart: 'palette',
  hexbin: 'scale legend cartesian',
  density2d: 'scale legend cartesian',
  splom: 'palette legend',
  connectedScatter: 'palette legend cartesian',
  parallel: 'palette legend',
  chord: 'palette legend',
  arcDiagram: 'palette legend',
  adjacency: 'scale legend cartesian',
  network: 'palette legend',
  network3d: 'palette legend',
  sankey: 'palette',
  alluvial: 'palette legend',
  gantt: 'palette legend cartesian',
  timeline: 'palette legend cartesian',
  calendar: 'scale legend',
  linearGauge: '',
  progressRing: 'palette legend',
  stat: 'palette',
  ohlc: 'updown cartesian',
  heikinAshi: 'updown cartesian',
  volumeProfile: 'palette updown cartesian',
  renko: 'updown legend cartesian',
  pointFigure: 'updown legend cartesian',
  kagi: 'updown legend cartesian',
  depth: 'updown legend cartesian',
  choropleth: 'scale legend',
  bubbleMap: 'palette',
  flowMap: 'palette',
  hexbinMap: 'scale legend',
  globe: 'palette scale legend',
  contour: 'scale legend cartesian',
  vectorField: 'scale legend cartesian',
  spectrogram: 'scale legend cartesian',
  ternary: 'palette legend',
  smith: 'palette legend',
  mesh3d: 'scale legend',
  isosurface: 'scale legend',
  vectorField3d: 'scale legend',
  waterfall3d: 'scale legend',
  wordCloud: 'legend',
  pareto: 'palette legend cartesian',
  populationPyramid: 'palette legend cartesian',
  confidenceBand: 'palette legend cartesian',
  errorBar: 'palette legend cartesian',
  mindMap: 'palette',
  voronoi: 'palette legend cartesian',
  polarScatter: 'palette legend',
  confusionMatrix: 'scale legend',
  rocCurve: 'palette legend cartesian',
  macd: 'palette updown legend cartesian',
  rsi: 'palette cartesian',
  cartogram: 'palette',
  dotDensity: 'palette legend',
  baseline: 'updown legend cartesian',
  difference: 'palette legend cartesian',
  divergingBar: 'diverging legend cartesian',
  variwide: 'palette cartesian',
  variablePie: 'palette legend',
  parliament: 'palette legend',
  packedBubble: 'palette legend',
  quadrant: 'palette cartesian',
  stem: 'palette legend cartesian',
  jumpLine: 'palette legend cartesian',
  dotHistogram: 'palette cartesian',
  winLoss: 'palette legend',
  areaBump: 'palette legend cartesian',
  smallMultiples: 'palette',
  navigator: 'palette cartesian',
  windBarb: 'palette cartesian',
  radialTree: 'palette legend',
  edgeBundling: 'palette legend',
  radialHeatmap: 'scale legend',
  liquidGauge: 'palette',
  tileMap: 'scale legend',
  spikeMap: 'palette',
  densityMap: 'scale legend',
  map3d: 'scale legend',
  lineBreak: 'updown legend cartesian',
  hollowCandle: 'updown cartesian',
  hlc: 'updown cartesian',
  histogram2d: 'scale legend cartesian',
  streamline: 'scale legend cartesian',
};
